In [5]:
import pickle
import sqlite3
import numpy as np

# Initializing database
db = sqlite3.connect('test1.db')
cursor = db.cursor()

# Initializing table
cursor.execute("CREATE TABLE IF NOT EXISTS my_table(my_column BLOB, my_column2 BLOB)")

list1 = np.ndarray([1, 2, 3, 4])

data_pickled = pickle.dumps(list1, pickle.HIGHEST_PROTOCOL)

# The follwing line gives me the error
cursor.execute("INSERT INTO my_table (my_column, my_column2) VALUES (?, ?)",
    (sqlite3.Binary(data_pickled), "hi"))

db.commit()

In [6]:
cursor.execute('SELECT my_column FROM my_table')
for row in cursor.fetchall()[:5]:
    # BLOB field needs to be strinyfied with str() before loading with pickle
    data = pickle.loads(row[0])
    #print(row)
    print(data)
    print(" ")

[1 2 3 4]
 
[1 2 3 4]
 
[[[[  6.93420515e-310   4.66905665e-310   6.93420120e-310   6.93404565e-310]
   [  2.06559520e-313   6.93420120e-310   6.93404565e-310   3.33227272e-313]
   [  6.93420102e-310   6.37344683e-322   4.66905666e-310   6.93420515e-310]]

  [[  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]
   [  0.00000000e+000   0.00000000e+000   4.66905615e-310   2.42092166e-322]
   [  6.93420515e-310   4.66905682e-310   6.93420592e-310   6.93420587e-310]]]]
 


In [1]:
import pickle
import sqlite3

# Initializing database and cursor
star_data_db = sqlite3.connect('star_data1.db')
star_data_cursor = star_data_db.cursor()

# Retrieving star_data from database
star_data_cursor.execute('SELECT star_features FROM cep_1o')
for row in star_data_cursor.fetchall()[:5]:
    # BLOB field needs to be strinyfied with str() before loading with pickle
    data = pickle.loads(row[0])
    print(data)
    print(len(data))
    
# star_data_cursor.execute('SELECT star_data FROM astrouw_data')
# for row in star_data_cursor.fetchall()[:2]:
#     # BLOB field needs to be strinyfied with str() before loading with pickle
#     data = pickle.loads(str(row[0]))
#     print(data)
#     print(len(data))

# Close cursor and database    
star_data_cursor.close
star_data_db.close()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xac in position 4: ordinal not in range(128)